{% set name = "ami" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/ami/archive/refs/tags/{{ version }}.tar.gz
  sha256: a2ac1be42c6bd70fb6349815960293385316a91910b4af59a8415b2d11f94a43 

build:
  skip: True  # [win or osx]
  noarch: python
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - setuptools
    - python
    - pip
    - pytest-runner
  run:
    - python
    - dill
    - pyzmq
    - pyqtgraph
    - networkfox
    - psana
    - ipython
    - pint
    - qtpy
    - asyncqt
    - amityping
    - mypy
    - numba
    - h5py
    - pyarrow
    - scipy
    - pytest-qt
    - pytest-asyncio
    - sympy
    - pygraphviz
    - setproctitle
    - pyfftw
    - pyqode.python
    - qtconsole
    - prometheus_client

about:
  home: https://github.com/slac-lcls/ami
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'The LCLS-II online graphical analysis monitoring package'
  description: |
    ami is the online graphical anaylis package
    developed for LCLS-II.
  doc_url: https://github.com/slac-lcls/ami
  dev_url: https://github.com/slac-lcls/ami

extra:
  recipe-maintainers:
    - valmar
    - chrisvam

